---
- name: Check if ansible version is equal or greater than 2.11
  ansible.builtin.fail:
    msg: "Ansible core should be equal or greater than 2.11"
  when: ansible_version.full is ansible.builtin.version('2.11','<')

- name: Check if python is equal or greater than 3
  ansible.builtin.fail:
    msg: "Python should be equal or greater than 3"
  when: ansible_python.version.major is ansible.builtin.version('3','<')

# tasks file for samba
- name: Install samba services
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ samba_packages }}"
  tags: samba_install

- name: Set samba_config_params parameter
  ansible.builtin.include_vars: "{{ samba_vars_dir }}/main.yml"

- name: Config samba
  ansible.builtin.template:
    src: "{{ samba_templates_dir }}/smb.conf.j2"
    dest: "{{ samba_config_file }}"
    mode: "0644"
    validate: "testparm -s %s"

- name: Enable and start samba after configure
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: "restarted"
  loop: "{{ samba_services }}"
  when: samba_is_server is defined and samba_is_server | bool
