---
# handlers file for samba
- name: Enable samba
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  loop: "{{ samba_services }}"

- name: Disable samba
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
  loop: "{{ samba_services }}"

- name: Start samba
  ansible.builtin.service:
    name: "{{ item }}"
    state: "started"
  loop: "{{ samba_services }}"

- name: Stop samba
  ansible.builtin.service:
    name: "{{ item }}"
    state: "stopped"
  loop: "{{ samba_services }}"

- name: Restart samba
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
  loop: "{{ samba_services }}"

- name: Reload samba
  ansible.builtin.service:
    name: "{{ item }}"
    state: "reloaded"
  loop: "{{ samba_services }}"
